export const autoGenerativeContent = `We are an innovative Solar energy Engineering, Procurement and Construction (EPC) Company focused on solar rooftops and Ground Mounted power plants. We specialize in off grid and grid connected solar power plants specifically for residential homes, commercial offices & industries.
Our Company is motivated by UN Sustainable Development Goals to provide Affordable & Clean Energy to Everyone and taking necessary actions against Climate Change by 2030. We aim to focus on developing solar power as a sustainable source of alternative energy in India and make solar a household utility for everyone. Our solar plants also helps save on the electricity bills upto 30-50% (or 100%) for our industries paying higher tariffs and add to their bottom line.

We are committed to provide solar solutions to our clients customized to their requirements as per the site conditions. Our core values are to deliver Quality and Efficient Solar power systems to last for 25 years.`; // for portfolio page

export const autoGenerativeContentForPortfolioPolicy = `Our After Sales team is specifically trained and experienced about the technical characteristics of our solar plants. This allows for quick, effective and reliable in-house assistance for any issue. 

The After Sales service offers 24/7 support through remote assistance tools and with on-site visits by experienced members of our maintenance team when required. Our after sales service support to our customers has resulted in record availability, > 99% for all of our plants under service contracts.`;

export const autoGenerativeContentForProjectDescription = `This project involves the setting up of a solar power project at Amravati, Maharashtra. The solar plant will have a capacity of 100 MW and will generate electricity which will be used as an utility.
The project activity will therefore displace an equivalent amount of electricity which would have otherwise been generated by a fossil-fuel dominant grid & contributes to helping accelerate a transition to a low-carbon energy mix.`;
