import { Box, Container, styled, Typography } from '@mui/material';
import React from 'react';
import BlogIntroSection from '../../../components/BlogIntroSection/BlogIntroSection';
import DownloadFeatureBox from '../../../components/SolarDesignComps/DownloadFeatureBox';

const Wrapper = styled(Box)(({ theme }) => ({
   paddingBottom: '2rem',
   background: '#F3F3F3',
}));
const FeatureBox = styled(Box)(({ theme }) => ({
   display: 'flex',
   justifyContent: 'space-around',
   margin: '3rem 0',
}));

const Feature = styled(Box)(({ theme }) => ({
   background: theme.palette.primary.main,
   borderRadius: '5px',
   padding: '1rem',
   maxWidth: '11rem',
   textAlign: 'center',
   display: 'flex',
   justifyContent: 'center',
   alignItems: 'center',
   boxShadow: '0px 4px 15px rgba(0, 0, 0, 0.2)',
}));

const Flex = styled(Box)(({ theme }) => ({
   display: 'flex',
   justifyContent: 'space-around',
}));

const GrayBox = styled(Box)(({ theme }) => ({
   background: theme.palette.secondary.light,
   padding: '1rem',
   borderRadius: '5px',
   marginRight: '1rem',
   display: 'flex',
   justifyContent: 'center',
   alignItems: 'center',
   width: '30%',
   '& p': {
      textAlign: 'center',
   },
   boxShadow: '0px 4px 15px rgba(0, 0, 0, 0.2)',
   '&:last-child': {
      marginRight: 0,
   },
}));

const description1 = `3D solar designs are made by analyzing your project’s site survey data and provide a complete 360° Bird Eye View of all sides including the top position of the solar system design. It gives a reference with which the solar modules and other components, mounting structure and foundation equipment will be placed with the aim to minimize the area for project and maximum energy generation. With 3D solar designs, one can even detect and prepare for future circumstances that may arise in project execution due to discrepancies in the site.`;

const description2 = `Shadow analysis targets the plant inefficiencies namely, hot-spot effects on panels and low current generation caused by shadow on panels. Solar power plants must be in a 100% shadow-free area to get optimum generation. So while designing the solar power plant, we need to consider the sun position throughout the year and our site location azimuth. Shadow analysis is 97% accurate, and to make a site 100% shadow-free, one should do shadow analysis on 22nd December and 21st June for a given location. If the site is shadow-free on these days, then shadow won’t be cast on panels in an entire year because these days are the shortest and longest days respectively. While making the 3D shadow model, we should also consider the height of the solar power plant and azimuth of the project as well.`;

const description3 = `PV-SYST generation report provides precise forecasts on energy generation to calculate the power output and exact ROI of the given plant. It provides an overview on the efficiency of the plant operation along with the effect of losses due to equipment, shadow and other environmental conditions. It also takes into account the increasing inefficiencies of solar components over time while providing monthly electricity units generated by a system during a period of 25 years. A PV-SYST report helps in deciding the following factors`;

const SolarDesign = () => {
   return (
      <Wrapper>
         <BlogIntroSection
            sx={{ mb: 9 }}
            title='Solar Design'
            backgroundImageUrl='https://i.ibb.co/HnGLwxw/image-6-4.png'
         />

         <Container maxWidth='lg'>
            <Typography sx={{}}>
               As the solar industry has grown, an increasing number of people
               are becoming familiar with the environmental and financial
               benefits associated with owning a solar system. Despite this
               increase in interest, the process in which these systems are
               designed has remained a mystery to many. Outfitting your rooftop
               with an adequate solar PV design for a solar panel is the first
               step to a lifetime experience of sustainable solar energy. Solar
               designs help one understand the technical parameters and Return
               on Investment (ROI) for a given project. Here we will take you
               through the basics of solar system design and the considerations
               that shape a final system. A solar design balances the 4
               parameters mentioned below:
            </Typography>

            <FeatureBox>
               <Feature>
                  <Typography sx={{ fontSize: '1.2rem', fontWeight: 'bold' }}>
                     MINIMUM PROJECT COST
                  </Typography>
               </Feature>
               <Feature>
                  <Typography sx={{ fontSize: '1.2rem', fontWeight: 'bold' }}>
                     MAXIMUM ENERGY GENERATION
                  </Typography>
               </Feature>
               <Feature>
                  <Typography sx={{ fontSize: '1.2rem', fontWeight: 'bold' }}>
                     MAXIMUM STABILITY & STRENGTH OF PLANT
                  </Typography>
               </Feature>
               <Feature>
                  <Typography sx={{ fontSize: '1.2rem', fontWeight: 'bold' }}>
                     MINIMUM USE OF LAND AREA
                  </Typography>
               </Feature>
            </FeatureBox>

            <Typography
               sx={{ fontWeight: 'bold', textAlign: 'center', mb: 3 }}
               variant='h6'
            >
               A Solar Design consists of the following components
            </Typography>

            <DownloadFeatureBox
               title='3D SOLAR PANEL PLACEMENT AND STRUCTURE DESIGN'
               description={description1}
               downloadButtonText='Sample 3D Design report'
            />

            <DownloadFeatureBox
               title='SHADOW ANALYSIS'
               description={description2}
               downloadButtonText='Sample Shadow analysis report'
            />

            <DownloadFeatureBox
               title='SHADOW ANALYSIS'
               description={description3}
               downloadButtonText='Sample PV-SYST generation report'
            >
               <Flex sx={{mb: 3}}>
                  <GrayBox>
                     <Typography>
                        SELECTION OF SOLAR PANELS, INVERTERS AND OTHER
                        COMPONENTS
                     </Typography>
                  </GrayBox>
                  <GrayBox>
                     <Typography>
                        STRING DISTRIBUTION BASED ON SOLAR INVERTER MPPT
                     </Typography>
                  </GrayBox>
                  <GrayBox>
                     <Typography>
                        AC/ DC COMBINER BOX DESIGN AND ITS COMPONENT SELECTION
                     </Typography>
                  </GrayBox>
               </Flex>
               <Flex>
                  <GrayBox>
                     <Typography>
                        SELECTION OF SOLAR PANELS, INVERTERS AND OTHER
                        COMPONENTS
                     </Typography>
                  </GrayBox>
                  <GrayBox>
                     <Typography>
                        STRING DISTRIBUTION BASED ON SOLAR INVERTER MPPT
                     </Typography>
                  </GrayBox>
                  <GrayBox>
                     <Typography>
                        AC/ DC COMBINER BOX DESIGN AND ITS COMPONENT SELECTION
                     </Typography>
                  </GrayBox>
               </Flex>
            </DownloadFeatureBox>
         </Container>
      </Wrapper>
   );
};

export default SolarDesign;
